# Increment version in package.json and create tag

name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: git config --global user.name 'Lime Tracker GitHub'
      - run: git config --global user.email 'noreplay@lime-tracker.com'
      - run: git config --global push.followTags true
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
